# Generated by Django 4.2.4 on 2023-08-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=210)),
            ],
        ),
    ]
